# iDigital Smart home WIFI Power Plug with USB Port
# -----------------------
# Brand: iDigital
# Model: 30099179 Plug with USB
# I refer to it as  iDigital Smart Plug.
# Uses a ESP8266-S3 wifi module.
# Has blue and red LED
# Tasmota Template: None existed, GPIO4 - Red LED, GPIO12 - Relay, GPIO13 - Button

substitutions:
# ESPHome nodename
  devicename: idigital_smart_plug
# A prettier name
  upper_devicename: iDigital Smart Plug

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SSID"
  password: "PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename}_fallback"
    password: "PASSWORD"

captive_portal:

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: "PASSWORD"

ota:
  password: "PASSWORD"
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${upper_devicename}_button"
    #toggle both relays on push, and turns led on
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

switch:
  - platform: gpio
    id: red_led
    pin:
      number: GPIO4
      inverted: True
  - platform: gpio
    name: "${upper_devicename}_relay"
    pin: GPIO12
    id: relay

    # Turns red LED off .
    # Plug doesnt let you disable blue led.
    # You can get purple if you turn it on.
    on_turn_on:
      - switch.turn_off: red_led

    # Turns red LED on
    # Plug doesnt let you disable blue led.
    # You can get purple if you turn both on.
    on_turn_off:
      - switch.turn_on: red_led
