# ARLEC Grid Connect GLD110HA Globe with CW and WW
# -----------------------
# Brand: Arlec Grid Conenct
# Model: GLD110HA
# Runs Brightness pin and colour temperature pin. Uses TYWE3L wifi module, inbuilt gamma correction, standard ESPhome cwww platform will not work. 
# To use this YAML template you need to place "CWWWSinglepintempandbrightnessLightOutput.h" into the config/esphome/ directory.
# Tasmota Template: {"NAME":"Arlec CCT","GPIO":[0,0,0,0,0,37,0,0,0,38,0,0,0],"FLAG":0,"BASE":48}
# Take special note at Line 24 to ensure your ok with this, if not comment it out and uncomment line 59.





substitutions:
# ESPHome nodename
  devicename: arlec_gld110ha_grid_connect_globe_1
# A prettier name
  upper_devicename: Arlec GLD110HA Globe

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true # You will kill the ESP module by using this with high occurance changes, but is the only way to get the led temp and brightness back to your setting. https://esphome.io/components/esphome.html#esphome-esp8266-restore-from-flash
  includes:
  - CWWWSinglepintempandbrightnessLightOutput.h

wifi:
  ssid: "SSID"
  password: "PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Arlec Gld110Ha Globe 1"
    password: "PASSWORD"

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: "PASSWORD"

ota:
  password: "PASSWORD"

light:
  - platform: custom
    lambda: |-
      auto light_out = new CWWWSinglepintempandbrightnessLightOutput(id(output_brightness), id(output_temp));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: $upper_devicename
        # Uncomment below if your not using restore from flash above, you will loose the previous set brightness and temp.
        #restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: output_temp
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_brightness
    pin: GPIO5

